apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-services-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Geoffrey-Anto/microservices-deployment.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true