apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Enter deployment name
spec:
  replicas: Enter the number of replicas
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: proxy
        image: geoffreyanto12/proxy:latest
        resources:
            limits:
              memory: "256Mi"
              cpu: "1"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    NodePort: 30005
